apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.scriptName }}
data:
  script.sh: |
     #!/bin/bash
     # Get the PID of the running Nginx process
     PID=$(cat /var/run/nginx.pid)
     
     # Gracefully stop Nginx
     nginx -s quit
     
     # Wait until the Nginx process has terminated
     while [ -d /proc/$PID ]; do
       sleep 0.1
     done
